version: '3.8'

networks:
  hw3_bridge:
    external: true

services:
  backend:
    image: "ghcr.io/ds-hw-fuuzen/hw2-backend:master"
    environment:
      - BKPAAS_APP_ID=${YOUR_APP_ID}
      - BKPAAS_APP_SECRET=${YOUR_APP_SECRET}
      - BKPAAS_MAJOR_VERSION=3
      - BK_PAAS2_URL=https://ce.bktencent.com
      - BK_COMPONENT_API_URL=https://bkapi.ce.bktencent.com
      - BKPAAS_LOGIN_URL=https://ce.bktencent.com/login/
      - DEV_DB_HOST=db
      - DEV_DB_PORT=3306
      - DEV_DB_USER=root
      - DEV_DB_PASSWORD=root
      - DEV_DB_NAME=${YOUR_APP_ID}
      - CORS_ALLOWED_ORIGIN=http://dev.ce.bktencent.com:5000
      - BKPAAS_JOB_URL=https://job.ce.bktencent.com
    depends_on:
      - db
    volumes:
      - ${HOME}/.ssh:/root/.ssh
    networks:
      - hw3_bridge

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${YOUR_APP_ID}
      # MYSQL_USER: 
      # MYSQL_PASSWORD: 
    # volumes:
    #   - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - hw3_bridge

# volumes:
#   db_data: {}